"""
Test Auto Loader

This file is used to automatically load all tests from app.api submodules.

DO NOT EDIT THIS FILE.

"""
import pkgutil
import unittest

from django.conf import settings


def load_tests(
    loader: unittest.loader.TestLoader,
    tests: unittest.suite.TestSuite,
    _pattern: str,
) -> unittest.suite.TestSuite:
    """
    Iterate app.api submodules, look for a module called PACKAGE_NAME_tests.py and load the tests,
     appending them to the tests list

    Example folder structure:
        - app/api/example/example_tests.py

    """
    base_path = settings.BASE_DIR / "app" / "api"
    # Iterate app.api submodules
    for module in pkgutil.iter_modules([base_path]):
        # Look for a submodule (file) called PACKAGE_NAME_tests.py
        for submodule in pkgutil.iter_modules([base_path / module.name]):
            if submodule.name.endswith("_tests"):
                # Load the tests, appending them to the tests list
                tests.addTests(loader.loadTestsFromName(f"app.api.{module.name}.{submodule.name}"))
    return tests
